version: 2.1
orbs:
  elixir: membraneframework/elixir@1

executors:
  docker-executor:
    docker:
      - image: ghcr.io/jellyfish-dev/recording-converter-test:0.0.1
        environment:
          MIX_ENV: test

jobs:
  test:   # test job is defined here
    executor: docker-executor
    steps:
      - setup_remote_docker
      - checkout
      - run: mix deps.get
      - run: MIX_ENV=test mix compile
      - run: mix test --warnings-as-errors




workflows:
  version: 2
  build:
    jobs:
      - elixir/build_test:
          filters: &filters
            tags:
              only: /v.*/
      - test
      - elixir/lint:
          filters:
            <<: *filters
