version: 2.1
orbs:
  elixir: membraneframework/elixir@1

executors:
  docker-executor:
    docker:
      - image: ghcr.io/jellyfish-dev/recording-converter-test:0.0.3
        environment:
          MIX_ENV: test
jobs:
  test:
    executor: docker-executor
    steps:
      - setup_remote_docker
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "mix.lock" }}
      - run: mix deps.get
      - save_cache:
          key: v1-deps-{{ checksum "mix.lock" }}
          paths:
            - deps
      - run: MIX_ENV=test mix compile --force
      - run: mix test --warnings-as-errors




workflows:
  version: 2
  build:
    jobs:
      - elixir/build_test:
          filters: &filters
            tags:
              only: /v.*/
    #   - test
    #   - elixir/lint:
    #       filters:
    #         <<: *filters
